---
title: "Breast Cancer_Classification model"
author: "Prathibha"
date: "3/18/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
```{r}
##Loading the BreastCancer dataset from mlbench

require(mlbench)
data(BreastCancer)
```


```{r}
##Removing null values in the dataset
library(mice)  

dataset_impute <- mice(BreastCancer[,2:10],  print = FALSE)

BreastCancer <- cbind(BreastCancer[,11, drop = FALSE], mice::complete(dataset_impute, 1))

```

```{r}
##SVM Model

head(BreastCancer)
library(e1071)
mysvm <- svm(Class ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)

```
```{r}

#Naive Bayes classification model
library(klaR)
mynb <- NaiveBayes(Class ~ ., BreastCancer)
mynb.pred <- predict(mynb,BreastCancer)
table(mynb.pred$class,BreastCancer$Class)


```

```{r}


##Neural Network model
library(nnet)
mynnet <- nnet(Class ~ ., BreastCancer, size=1)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
table(mynnet.pred,BreastCancer$Class)


```


```{r}
library(MASS)

#Decision trees
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) # in "iris_tree.ps"
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)


```

```{r}

# Leave-1-Out Cross Validation (LOOCV)
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```


```{r}

#Quadratic Discriminant Analysis

library(MASS)
df<-BreastCancer
df2<-df
#convert to integers 

df2$Cl.thickness<-as.integer(df$Cl.thickness)
df2$Mitoses<-as.integer(df$Mitoses)
df2$Cell.size<-as.integer(df$Cell.size)
df2$Cell.shape<-as.integer(df$Cell.shape)
df2$Marg.adhesion<-as.integer(df$Marg.adhesion)
df2$Epith.c.size<-as.integer(df$Epith.c.size)
df2$Bare.nuclei<-as.integer(df$Bare.nuclei)
df2$Bl.cromatin<-as.integer(df$Bl.cromatin)
df2$Normal.nucleoli<-as.integer(df$Normal.nucleoli)

head(df2)
myqda <- qda(Class ~ ., data=df2)
myqda.pred <- predict(myqda, df2)
table(myqda.pred$class,df2$Class)

```


```{r}


#Regularised Discriminant Analysis

library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)
table(myrda.pred$class,BreastCancer$Class)

```

```{r}
#Random Forests

library(randomForest)
myrf <- randomForest(Class ~ .,BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
table(myrf.pred, BreastCancer$Class)

```
```{r}
#The majority vote Ensemble approach 

finalPred <-as.factor(ifelse(myrf.pred=='benign' & myrda.pred =='benign','benign',ifelse(myrf.pred=='benign' & myqda.pred=='benign','benign',ifelse(myrda.pred=='benign' & myqda.pred=='benign','benign','malignant'))))
finalPred



```

